[tool.poetry]
name = "hello-gradio"
version = "0.1.0"
description = ""
authors = ["Naosuke Ito <Naosuke.Ito@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
